input {
  beats {
    port => 5044
  }
}

filter {
  if [fields][app] == "kaba-delivery" {
    grok {
      match => {
        "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] %{DATA:environment}\.%{LOGLEVEL:level}: %{GREEDYDATA:log_message}"
      }
    }

    # Filtre spécial erreurs HTTP 500 (exigé par l'épreuve)
    if [level] == "ERROR" {
      mutate {
        add_tag => ["http_500_error", "kaba-delivery-error"]
      }
    }

    date {
      match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "kaba-delivery-logs-%{+YYYY.MM.dd}"
  }
}