global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métriques Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métriques CPU/RAM du serveur (exigé par l'épreuve)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Métriques application Kaba-Delivery
  - job_name: 'kaba-delivery'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics
    scrape_interval: 10s