sonar.projectKey=lustrellesobze_tp_camwater
sonar.organization=lustrellesobze
sonar.projectName=Kaba-Delivery
sonar.projectVersion=1.0

sonar.sources=app,routes,database
sonar.tests=tests
sonar.language=php
sonar.php.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
sonar.sourceEncoding=UTF-8
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/cache/**