# Identification du projet
sonar.projectKey=kaba-delivery
sonar.projectName=Kaba-Delivery
sonar.projectVersion=1.0

# Sources à analyser
sonar.sources=app,routes,database
sonar.tests=tests
sonar.language=php

# Rapports de couverture de tests
sonar.php.coverage.reportPaths=coverage.xml

# Quality Gate strict (exigé par l'épreuve)
# Échec si couverture < 80% ou vulnérabilité High détectée
sonar.qualitygate.wait=true

# Encodage
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=vendor/**,node_modules/**,public/**,storage/**,bootstrap/cache/**